[package]
name = "my_thesis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p256 = "0.9.0"
hex = "0.4.3"
rand_core = "0.6.3"
secp256k1 = "0.28.1"
ecies = "0.2.6"
sha2 = "0.10.8"